name: Tagwikifrontend

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: docker build -t hazell3/tagwikifrontend .

      - name: Publish Image to Docker Hub
        run: docker push hazell3/tagwikifrontend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull hazell3/tagwikifrontend:latest

      - name: Delete old container if exists
        run: |
          docker ps -a -q --filter "name=reactjs-app-container" | grep -q . && docker rm -f reactjs-app-container || echo "No container found"

      - name: Run Docker Container

        run: docker run -d -p 3000:80 --name reactjs-app-container hazell3/tagwikifrontend

